import jenkins.model.*

pipeline {
    agent {
        label "Deploy"
    }

    stages {
        stage('cleanup') {
            steps {
                // Delete the zip
                sh script: "rm -f artifact.zip"

                // Delete the folder
                sh script: "rm -fR artifactExtract"
            }
        }

        stage('deploy') {
            when {
                expression { return env.NODE_LABELS.contains(env.COMPONENT_NAME) }
            }

            steps {
                echo "NODE_NAME = ${env.NODE_NAME}"

                echo "Find artifact"
                sh script: "curl -u download:password \"http://nexus.jbrmmg.me.uk:8081/service/rest/v1/search/assets?sort=version&direction=desc&repository=${env.REPOSITORY_NAME}&group=${env.COMPONENT_GROUP}&name=${env.COMPONENT_NAME}&version=${env.COMPONENT_VERSION}&maven.extension=zip\" --output ./response.xml"

                echo "Artifact download URL"
                sh script: "cat response.xml | grep -Po '\"downloadUrl\" : \"\\K.+(?=\",)'"

                echo "Download"
                sh script: "cat response.xml | grep -Po '\"downloadUrl\" : \"\\K.+(?=\",)' | xargs curl -f -o artifact.zip"

                // Unzip the files
                unzip zipFile: "artifact.zip", dir: "artifactExtract"

                // Clean up.
                sh script: "rm -f artifact.zip"
            }
        }
    }
}
